### ISSUE TITLE
Duplicate CLI flag -h

### ISSUE THREAD

**Issue by wappsify** [neoskop/s3surgeon#5]
The CLI flag `-h` as the short version of the `--hashfile` conflicts with the default `-h` / `--help` flag of the `commandeer` package, making the help command available only via `s3surgeon --help`. 

Using the commmand `s3surgeon -h`, the package will always try and interpret the input as if the user wanted to use the `--hashfile` flag.

The short flag for `--help` may be changed using `.helpOption()` as is documented [here](https://www.npmjs.com/package/commander#helpoptionflags-description).

**Comment by arnediekmann** [comment]
This has been fixed be renaming the short flag of `hashfile` to `-H` to be more consistent with other CLIs which use `-h` for help. Since this is a breaking change this is released as `1.0.0` :confetti_ball:
